//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class webserviceEntities : DbContext
    {
        public webserviceEntities()
            : base("name=webserviceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<produto> produto { get; set; }
        public DbSet<produtocategoria> produtocategoria { get; set; }
    
        public virtual ObjectResult<uspConsultarProduto_Result> uspConsultarProduto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspConsultarProduto_Result>("uspConsultarProduto");
        }
    }
}
