//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int ProdutoId { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> ProdutoCategoriaId { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual produtocategoria produtocategoria { get; set; }
    }
}
