//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vproduto_categoria
    {
        public int Id { get; set; }
        public string ProdutoDesc { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public int CategoriaId { get; set; }
        public string CategoriaDesc { get; set; }
    }
}
